export interface Collection {
  id: number;
  name: string;
  slug: string;
  color?: string | null;
  // Tocas UI icon class name, e.g. 'is-comments-icon'
  icon?: string | null;
  parentId?: number | null;
}

export const COLLECTIONS: readonly Collection[] = [
  {
    id: 1,
    name: '網站建議/回報',
    slug: 'official-2',
    color: '#888',
    icon: 'is-wrench-icon',
    parentId: null,
  },
  {
    id: 2,
    name: '站方',
    slug: 'official',
    color: '#575D90',
    icon: 'is-user-shield-icon',
    parentId: null,
  },
  {
    id: 3,
    name: '集中串',
    slug: 'concentrated',
    color: '#008994',
    icon: 'is-layer-group-icon',
    parentId: null,
  },
  {
    id: 4,
    name: '綜合',
    slug: 'all',
    color: '#0471A6',
    icon: 'is-comment-dots-icon',
    parentId: null,
  },
  {
    id: 5,
    name: '閒聊',
    slug: 'chat',
    color: '#37718E',
    icon: 'is-comments-icon',
    parentId: 4,
  },
  {
    id: 6,
    name: '廢文',
    slug: 'shitpost',
    color: '#15AABF',
    icon: 'is-box-open-icon',
    parentId: null,
  },
  {
    id: 7,
    name: '心情',
    slug: 'mood',
    color: '#AC2949',
    icon: 'is-heart-pulse-icon',
    parentId: null,
  },
  {
    id: 8,
    name: '認真',
    slug: 'serious',
    color: '#5c03eb',
    icon: 'is-envelope-open-text-icon',
    parentId: null,
  },
  {
    id: 9,
    name: '問題',
    slug: 'question',
    color: '#d45150',
    icon: 'is-circle-question-icon',
    parentId: 4,
  },
  {
    id: 10,
    name: '寶拉',
    slug: 'Paula',
    color: '#3A445D',
    icon: 'is-box-archive-icon',
    parentId: 4,
  },
  {
    id: 11,
    name: '八卦',
    slug: 'Gossiping',
    color: '#26408B',
    icon: 'is-comments-icon',
    parentId: 4,
  },
  {
    id: 12,
    name: '音樂',
    slug: 'music',
    color: '#3A445D',
    icon: 'is-music-icon',
    parentId: 4,
  },
  {
    id: 13,
    name: '動漫',
    slug: 'anime',
    color: '#417B5A',
    icon: 'is-tv-icon',
    parentId: 4,
  },
  {
    id: 14,
    name: '創作',
    slug: 'creation',
    color: '#CC3363',
    icon: 'is-pen-ruler-icon',
    parentId: null,
  },
  {
    id: 15,
    name: '教學',
    slug: 'teaching',
    color: '#F50853',
    icon: 'is-chalkboard-user-icon',
    parentId: 4,
  },
  {
    id: 16,
    name: '遊戲',
    slug: 'games',
    color: '#1E55FC',
    icon: 'is-gamepad-icon',
    parentId: null,
  },
  {
    id: 17,
    name: '推坑',
    slug: 'recommend',
    color: '#F783AC',
    icon: 'is-hand-holding-heart-icon',
    parentId: 4,
  },
  {
    id: 18,
    name: '程式',
    slug: 'code',
    color: '#2C497F',
    icon: 'is-code-icon',
    parentId: 4,
  },
  {
    id: 19,
    name: '政治',
    slug: 'political',
    color: '#A85102',
    icon: 'is-person-booth-icon',
    parentId: 4,
  },
  {
    id: 20,
    name: '新聞',
    slug: 'news',
    color: '#038030',
    icon: 'is-newspaper-icon',
    parentId: 4,
  },
  {
    id: 21,
    name: 'YouTuber',
    slug: 'youtuber',
    color: '#FF5505',
    icon: 'is-youtube-icon',
    parentId: 4,
  },
  {
    id: 22,
    name: '戲劇',
    slug: 'tv-series',
    color: '#FD7E19',
    icon: 'is-film-icon',
    parentId: 4,
  },
  {
    id: 23,
    name: '輔導級內容',
    slug: 'PG15',
    color: '',
    icon: 'is-circle-exclamation-icon',
    parentId: null,
  },
  {
    id: 24,
    name: '真人成人',
    slug: 'porn',
    color: '#FF0033',
    icon: 'is-triangle-exclamation-icon',
    parentId: 38,
  },
  {
    id: 25,
    name: '二次元成人',
    slug: 'porn-2',
    color: '#FF3300',
    icon: 'is-triangle-exclamation-icon',
    parentId: 38,
  },
  {
    id: 26,
    name: 'Nex 開發社群',
    slug: 'nex',
    color: '#96f',
    icon: 'is-terminal-icon',
    parentId: null,
  },
  {
    id: 27,
    name: '繪畫',
    slug: 'artist',
    color: '#aa3a00',
    icon: 'is-pen-icon',
    parentId: 14,
  },
  {
    id: 28,
    name: '小說',
    slug: 'writer',
    color: '#cc00bb',
    icon: 'is-book-open-icon',
    parentId: 14,
  },
  {
    id: 29,
    name: '封存',
    slug: 'Archive',
    color: '#116677',
    icon: 'is-file-zipper-icon',
    parentId: 1,
  },
  {
    id: 30,
    name: '處理中',
    slug: 'proccessing',
    color: '#0077ff',
    icon: 'is-server-icon',
    parentId: 1,
  },
  {
    id: 31,
    name: '公告',
    slug: 'announcement',
    color: '#555',
    icon: 'is-bullhorn-icon',
    parentId: 2,
  },
  {
    id: 32,
    name: '預告',
    slug: 'notice',
    color: '#666',
    icon: 'is-fire-icon',
    parentId: 2,
  },
  {
    id: 33,
    name: '規範',
    slug: 'term',
    color: '#888',
    icon: 'is-check-icon',
    parentId: 2,
  },
  {
    id: 34,
    name: '計畫',
    slug: 'plan',
    color: '#999',
    icon: 'is-rss-icon',
    parentId: 2,
  },
  {
    id: 35,
    name: '處分名單',
    slug: 'ban',
    color: '#f00',
    icon: 'is-ban-icon',
    parentId: 2,
  },
  {
    id: 36,
    name: 'VTuber',
    slug: 'VTuber',
    color: '#6bb2ee',
    icon: 'is-cloud-icon',
    parentId: 4,
  },
  {
    id: 37,
    name: '手冊',
    slug: 'manual',
    color: '#0af',
    icon: 'is-book-icon',
    parentId: 2,
  },
  {
    id: 38,
    name: '管制區',
    slug: 'restrict',
    color: '#f00',
    icon: 'is-circle-exclamation-icon',
    parentId: null,
  },
  {
    id: 39,
    name: '安價',
    slug: 'cheap',
    color: '#e102e3',
    icon: 'is-money-check-dollar-icon',
    parentId: 4,
  },
  {
    id: 40,
    name: '瀏覽器附加元件',
    slug: 'browser-exts',
    color: '',
    icon: 'is-globe-icon',
    parentId: 26,
  },
  {
    id: 41,
    name: 'Android',
    slug: 'android',
    color: '',
    icon: 'is-android-icon',
    parentId: 26,
  },
  {
    id: 42,
    name: 'iOS',
    slug: 'ios',
    color: '',
    icon: 'is-apple-icon',
    parentId: 26,
  },
  {
    id: 43,
    name: 'macOS',
    slug: 'macos',
    color: '',
    icon: 'is-laptop-icon',
    parentId: 26,
  },
  {
    id: 44,
    name: 'Web',
    slug: 'web',
    color: '',
    icon: 'is-firefox-browser-icon',
    parentId: 26,
  },
  {
    id: 45,
    name: '其他',
    slug: 'other',
    color: '',
    icon: 'is-arrow-up-right-from-square-icon',
    parentId: 26,
  },
  {
    id: 46,
    name: '開發文獻',
    slug: 'documentation',
    color: '',
    icon: 'is-book-icon',
    parentId: 26,
  },
  {
    id: 47,
    name: 'Windows',
    slug: 'windows',
    color: '',
    icon: 'is-windows-icon',
    parentId: 26,
  },
  {
    id: 48,
    name: 'Linux',
    slug: 'linux',
    color: '',
    icon: 'is-linux-icon',
    parentId: 26,
  },
  {
    id: 49,
    name: '英雄聯盟',
    slug: 'league-of-legends',
    color: '',
    icon: 'is-shield-halved-icon',
    parentId: 16,
  },
  {
    id: 50,
    name: 'Apex 英雄',
    slug: 'apex',
    color: '',
    icon: 'is-crosshairs-icon',
    parentId: 16,
  },
  {
    id: 51,
    name: '絕地求生',
    slug: 'pubg',
    color: '',
    icon: 'is-person-rifle-icon',
    parentId: 16,
  },
  {
    id: 52,
    name: '手機平台',
    slug: 'mobile-platform',
    color: '',
    icon: 'is-mobile-screen-icon',
    parentId: 16,
  },
  {
    id: 53,
    name: '桌機平台',
    slug: 'pc-platform',
    color: '',
    icon: 'is-desktop-icon',
    parentId: 16,
  },
  {
    id: 54,
    name: 'PS 平台',
    slug: 'ps-platform',
    color: '',
    icon: 'is-playstation-icon',
    parentId: 16,
  },
  {
    id: 55,
    name: 'XBOX 平台',
    slug: 'xbox-platform',
    color: '',
    icon: 'is-xbox-icon',
    parentId: 16,
  },
  {
    id: 56,
    name: '其他平台',
    slug: 'other-platform',
    color: '',
    icon: 'is-chess-knight-icon',
    parentId: 16,
  },
  {
    id: 57,
    name: '情報',
    slug: 'game-news',
    color: '',
    icon: 'is-newspaper-icon',
    parentId: 16,
  },
  {
    id: 58,
    name: '攻略',
    slug: 'walkthrough',
    color: '',
    icon: 'is-puzzle-piece-icon',
    parentId: 16,
  },
  {
    id: 59,
    name: '其他遊戲',
    slug: 'other-game',
    color: '',
    icon: 'is-gamepad-icon',
    parentId: 16,
  },
  {
    id: 60,
    name: '貓貓',
    slug: 'meow',
    color: '#116688',
    icon: 'is-cat-icon',
    parentId: 4,
  },
  {
    id: 61,
    name: '決戰！平安京',
    slug: 'onmyoji arena',
    color: '',
    icon: 'is-torii-gate-icon',
    parentId: 16,
  },
  {
    id: 62,
    name: '傳說對決',
    slug: 'aov',
    color: '',
    icon: 'is-gamepad-icon',
    parentId: 16,
  },
] as const;

export const COLLECTIONS_MAP: Record<number, Collection> = Object.fromEntries(
    COLLECTIONS.map((c) => [c.id, c]),
);

export const COLLECTIONS_BY_SLUG: Record<string, Collection> =
  Object.fromEntries(
      COLLECTIONS.map((c) => [c.slug, c]),
  );
